/**
 * The deploy scaffold every new space gets.
 *
 * One Dockerfile that serves whatever the space holds — a Node app if there is
 * a package.json, otherwise the static files — so a space is deployable from
 * the moment it exists instead of after someone hand-writes container config.
 * Railway builds this same Dockerfile, which keeps `docker compose up` locally
 * and `railway up` in production running the identical image.
 */

/** Port both compose and Railway expose. Matches the space's open port. */
export const SCAFFOLD_PORT = 3000;

/** The CLI package the deployment installs so it can report in. */
export const CLI_PACKAGE = "@atlaslabsnpm/cli";

const DOCKERFILE = `# Generated by Atlas. Edit freely — it is your space's file.
FROM node:22-slim

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=${SCAFFOLD_PORT}

# The Atlas CLI, so the running container can report its live URL and post
# updates to everyone on the project. It authenticates with ATLAS_DEPLOY_TOKEN,
# injected at deploy time — there is no login inside a container.
RUN npm i -g ${CLI_PACKAGE} || echo "atlas cli unavailable; deploy reporting disabled"

COPY . .

# Install and build only when this is a Node project; a plain static site
# needs neither, and failing the build over a missing package.json would make
# the scaffold useless for half the things people host.
RUN if [ -f package.json ]; then \\
      (npm ci --omit=dev || npm install --omit=dev) && \\
      (npm run build --if-present || true); \\
    fi

EXPOSE ${SCAFFOLD_PORT}

ENTRYPOINT ["/app/atlas-entrypoint.sh"]
`;

/**
 * Start the app, then tell Atlas where it is.
 *
 * The report happens *after* the server is listening and never blocks it: a
 * deployment that serves traffic but fails to check in is a working deployment
 * with a missing notification, and that is the right way round.
 */
const ENTRYPOINT = `#!/bin/sh
# Generated by Atlas.
set -e

start_app() {
  if [ -f package.json ] && node -e "process.exit(require('./package.json').scripts?.start?0:1)" 2>/dev/null; then
    npm start
  else
    npx --yes serve -s . -l "\${PORT:-${SCAFFOLD_PORT}}"
  fi
}

report_ready() {
  [ -n "$ATLAS_DEPLOY_TOKEN" ] || return 0
  command -v atlas >/dev/null 2>&1 || return 0

  url="$ATLAS_PUBLIC_URL"
  # Railway exposes the generated hostname; prefer it over guessing.
  [ -z "$url" ] && [ -n "$RAILWAY_PUBLIC_DOMAIN" ] && url="https://$RAILWAY_PUBLIC_DOMAIN"
  [ -n "$url" ] || return 0

  # Wait for the port to answer before claiming the deployment is live.
  i=0
  while [ $i -lt 60 ]; do
    if node -e "require('net').connect(process.env.PORT||${SCAFFOLD_PORT},'127.0.0.1').on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))" 2>/dev/null; then
      atlas vm ready --url "$url" || true
      return 0
    fi
    i=$((i+1))
    sleep 2
  done
}

report_ready &
start_app
`;

const COMPOSE = `# Generated by Atlas. \`docker compose up\` runs the same image Railway builds.
services:
  web:
    build: .
    ports:
      - "${SCAFFOLD_PORT}:${SCAFFOLD_PORT}"
    environment:
      # 0.0.0.0 matters: a server bound to localhost is unreachable from
      # outside the container, and from outside the space.
      HOST: 0.0.0.0
      PORT: "${SCAFFOLD_PORT}"
      # Set locally to exercise the same reporting path a deploy uses.
      ATLAS_DEPLOY_TOKEN: "\${ATLAS_DEPLOY_TOKEN:-}"
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
`;

const RAILWAY_JSON = `{
  "$schema": "https://railway.app/railway.schema.json",
  "build": { "builder": "DOCKERFILE", "dockerfilePath": "Dockerfile" },
  "deploy": {
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 3
  }
}
`;

const DOCKERIGNORE = `.git
node_modules
.env
.env.*
*.log
.next/cache
`;

/**
 * Files written into a fresh space. Keyed by path relative to /workspace.
 * Exported so the deploy path can tell "no scaffold" from "user deleted it".
 */
export const SCAFFOLD_FILES: Record<string, string> = {
  Dockerfile: DOCKERFILE,
  "atlas-entrypoint.sh": ENTRYPOINT,
  "docker-compose.yml": COMPOSE,
  "railway.json": RAILWAY_JSON,
  ".dockerignore": DOCKERIGNORE,
};

/** Scaffold files that must be executable once they land in the space. */
export const SCAFFOLD_EXECUTABLE = ["atlas-entrypoint.sh"];
